# Generated by Django 5.1.6 on 2025-03-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_medical_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_role',
            field=models.CharField(blank=True, choices=[('nurse', 'Nurse'), ('doctor', 'Doctor')], max_length=225, null=True),
        ),
    ]
