# Generated by Django 5.1.6 on 2025-03-15 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_medical_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(max_length=225)),
                ('consultation_date', models.DateField()),
                ('consultation_time', models.TimeField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=225)),
                ('symptoms', models.TextField()),
                ('medical_history', models.TextField()),
                ('diagnosis', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_info_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
